### ISSUE TITLE
Problem importing into 7.0.0

### ISSUE THREAD

**Issue by dbdavidss** [bufanda/zabbix--template-xenorchestra#5] opened 2024-07-23 15:10 UTC
I tried importing the 6.4 template into 7.0.0 and got the error "Invalid parameter "/2/trends": value must be 0.".

I'm just starting to learn Zabbix so i don't know if the error is on my importing skills or if it just doesn't support 7.0.0 at the moment.

**Comment by bufanda** [comment] 2024-07-24 17:59
It doesn't import to 7.0 atm. I haven't tested it on 7.0 as I still need to setup a test instance for 7.0

I guess in Zabbix 7.0 something was removed or moved inside the template.

**Comment by brezlord** [comment] 2024-08-04 03:30
I had the same error trying to import the 6.4 version into Zabbix 6.4.16. The 6 version imported fine though.

**Comment by bufanda** [comment] 2024-08-04 18:49
> I had the same error trying to import the 6.4 version into Zabbix 6.4.16. The 6 version imported fine though.

Weird. Can't reproduce. Actually I create the 6.4 template by importing the 6.0 into 6.4 and the export it again. So if there is an issue it looks like that Zabbix is producing it itself.

**Comment by tuxpowered** [comment] 2024-08-13 18:49
I ran into the same issue, turns out that one of the docker containers was using a different version than the rest of them. 
Upgraded all docker images to the same version (6.4) and re-imported the templates and they loaded w/out issue.

**Comment by fh82** [comment] 2024-08-29 09:39
Same issue with 7.0.0. Successful Import with Version 7.0.3.

**Comment by bufanda** [comment] 2024-08-30 13:39
> Same issue with 7.0.0. Successful import with Version 7.0.3.

Please Read the [Readme](https://github.com/bufanda/zabbix--template-xenorchestra#tested-versions) Zabbix 7 Currently doesn't work at all. I wasn't able to test it further the past few week if it was fixed in-between.

**Comment by Fr0g-Not-Found** [comment] 2024-09-10 20:30
I built zabbix 7.0 from source and the Curl errors seem to be gone.  I was running into the same error while trying to email server reports.  Not sure if that would help or not.. I've imported the 7.0 template and it finds all of the vms... Just not getting resource usage.

**Comment by bufanda** [comment] 2024-09-11 10:29
@Fr0g-Not-Found Thanks for testing. I tried myself with the latest docker image and on the first glance it all seems to work. Discovery works and creted Items and hosts also get values. I imported the 6.4 template for start. Not sure if I broke the 7.0 while migrating back then. I'll take a look later tonight.

**Comment by billcouper81** [comment] 2024-09-11 22:54
Just adding my experience for comparison.

Apart from some issues with the Backup discovery (see issue #6) this worked for me since I first tried it on Zabbix 6.4 with XOA 5.9x. Since then I've upgraded Zabbix to 7.0, then 7.0.2, and now 7.0.3. And XOA has been upgraded through all stable channel releases to the current 5.95.2 version.

I only imported the template once back when I was running 6.4. I changed javascript for backups, but pretty sure everything else has 'just worked' so far. And it seems to find all of the hosts and VMs without issue. At least, I haven't noticed that I am missing anything.

**Comment by bufanda** [comment] 2024-09-12 03:50
> Just adding my experience for comparison.
> 
> Apart from some issues with the Backup discovery (see issue #6) this worked for me since 

backuo discovery never was really implemented that’s why it is disabled per default. I always meant to remove it as it basically gives no useful information in my opinion as it is not feasible to get the state of a backup like the last run failed without extensively parse the list of results and Zabbix will timeout when doing it or the JavaScript engine limits the memory used to load the list.

**Comment by billcouper81** [comment] 2024-09-12 04:04
I've got the backup discovery and monitoring working as mentioned in issue #6. So that it doesn't take as long I only process the backup logs until a match, from newest to oldest to always match the newest backup log as quickly as possible - I have 12 backup jobs to monitor and it is able to match them all in the script execution timeout window.

I am able to pull useful information such as the last run duration and status, with triggers on both. Combined with data from some other systems, such as the underlying backup storage, as well as additional per-VM data injected from the API, this is my current XOA Backups dashboard in Zabbix... still a work in progress, but it's getting there!

![xoa-bckup-dashboard](https://github.com/user-attachments/assets/f5e241e5-559f-40dc-9158-49cbeee01544)

**Comment by bufanda** [comment] 2024-11-21 13:34
Closing this issue due to inactivity.

**Closed by bufanda** 2024-11-21 13:34 UTC
